version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.19

orbs:
  codecov: codecov/codecov@3.3.0

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          # note: don't use `npm ci` as it installs the deps from the package-lock, which currently
          # causes problem with the arch specific packages, like @jakechampion/wizer-linux-x64
          command: |
            rm package-lock.json
            npm install
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"
      - run:
          name: Restore Google Credentials
          command: echo $GOOGLE_CREDS | base64 --decode | tee ~/.helix-google.json | jq -e .client_email

jobs:
  build:
    executor: node18
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test and Code Coverage
          command: npm run test
      - codecov/upload:
          flags: unittests
      - run:
          name: Prepare .wskprops
          command: |
            echo APIHOST=$WSK_APIHOST > ~/.wskprops
            echo NAMESPACE=$WSK_NAMESPACE > ~/.wskprops
            echo AUTH=$WSK_AUTH > ~/.wskprops
      - run:
          name: Integration Test and Code Coverage
          command: npm run integration-ci
      - codecov/upload:
          flags: integration
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Project Helix
